"""
Final Exam Part A — Feedback Analyzer
======================================
Reads feedback_log.json (the production interaction log) and reports:

    1. Total responses logged
    2. Count of negative feedback (feedback == "Bad")
    3. Top 3 failed queries grouped by user_input

It also groups failures by the tool the agent invoked so the report
surfaces *patterns*, not just raw failed strings.  Output goes to stdout
and is mirrored into analysis_report.md.

Run:
    python analyze.py                       # use feedback_log.json
    python analyze.py --log custom.json     # alternate log path
"""

import argparse
import json
import os
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).parent
DEFAULT_LOG = HERE / "feedback_log.json"
REPORT_PATH = HERE / "analysis_report.md"


def load_log(path: Path) -> list[dict]:
    if not path.exists():
        sys.exit(f"[ERROR] Feedback log not found: {path}")
    with path.open(encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        sys.exit(f"[ERROR] Expected a JSON array, got {type(data).__name__}")
    return data


def analyze(log: list[dict]) -> dict:
    total = len(log)
    negative = [x for x in log if x.get("feedback", "").lower() == "bad"]
    negative_count = len(negative)
    positive_count = total - negative_count

    # Top 3 failed queries — group by the exact user_input string so duplicates
    # surface as a pattern.  Falls back to listing each unique failed query
    # if all of them are distinct (typical for a small feedback set).
    failed_query_counts = Counter(x["user_input"] for x in negative)
    top_failed = failed_query_counts.most_common(3)

    # Group failures by which tool the agent invoked — useful signal when
    # every failed query is unique but the *tool path* is shared.
    tool_failure_counts = Counter()
    for x in negative:
        for t in x.get("tools_called", []) or ["<no_tool>"]:
            tool_failure_counts[t] += 1

    return {
        "total": total,
        "positive": positive_count,
        "negative": negative_count,
        "negative_rate": round(negative_count / total, 3) if total else 0.0,
        "top_failed_queries": top_failed,
        "failures_by_tool": tool_failure_counts.most_common(),
        "negative_records": negative,
    }


def render_report(stats: dict) -> str:
    lines: list[str] = []
    lines.append("# Feedback Analysis Report")
    lines.append("")
    lines.append("_Auto-generated by `analyze.py` — Final Exam Part A._")
    lines.append("")
    lines.append("## 1. Summary")
    lines.append("")
    lines.append(f"- **Total responses logged**: {stats['total']}")
    lines.append(f"- **Negative feedback (Bad)**: {stats['negative']}")
    lines.append(f"- **Positive feedback (Good)**: {stats['positive']}")
    lines.append(f"- **Negative rate**: {stats['negative_rate'] * 100:.1f}%")
    lines.append("")

    lines.append("## 2. Top 3 Failed Queries")
    lines.append("")
    if not stats["top_failed_queries"]:
        lines.append("_No negative feedback — nothing to rank._")
    else:
        lines.append("| # | Count | Query |")
        lines.append("|---|-------|-------|")
        for i, (query, n) in enumerate(stats["top_failed_queries"], 1):
            safe = query.replace("|", "\\|")
            lines.append(f"| {i} | {n} | {safe} |")
    lines.append("")

    lines.append("## 3. Failures by Tool Invoked")
    lines.append("")
    if not stats["failures_by_tool"]:
        lines.append("_No tool-level failure data._")
    else:
        lines.append("| Tool | Failures |")
        lines.append("|------|----------|")
        for tool, n in stats["failures_by_tool"]:
            lines.append(f"| `{tool}` | {n} |")
    lines.append("")

    lines.append("## 4. Negative Records (Full Detail)")
    lines.append("")
    if not stats["negative_records"]:
        lines.append("_None._")
    for rec in stats["negative_records"]:
        lines.append(f"### {rec['user_input']}")
        lines.append("")
        lines.append(f"- **Tools called**: `{rec.get('tools_called', [])}`")
        lines.append(f"- **Rationale**: {rec.get('rationale', '')}")
        lines.append("")
        lines.append("**Agent response**:")
        lines.append("")
        lines.append("```")
        lines.append((rec.get("agent_response") or "").strip())
        lines.append("```")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser(description="Analyze inventory agent feedback log.")
    p.add_argument("--log", type=Path, default=DEFAULT_LOG,
                   help=f"Path to feedback log JSON (default: {DEFAULT_LOG.name})")
    p.add_argument("--report", type=Path, default=REPORT_PATH,
                   help=f"Path to write the markdown report (default: {REPORT_PATH.name})")
    args = p.parse_args()

    log = load_log(args.log)
    stats = analyze(log)

    # ── Required exam output (printed to stdout) ────────────────────────
    print("=" * 60)
    print("FEEDBACK ANALYSIS")
    print("=" * 60)
    print(f"Total responses        : {stats['total']}")
    print(f"Negative feedback (Bad): {stats['negative']}")
    print()
    print("Top 3 Failed Queries:")
    if not stats["top_failed_queries"]:
        print("  (no failures)")
    else:
        for i, (q, n) in enumerate(stats["top_failed_queries"], 1):
            print(f"  {i}. [x{n}] {q}")
    print("=" * 60)

    # ── Persist the markdown report ──────────────────────────────────────
    report = render_report(stats)
    args.report.write_text(report, encoding="utf-8")
    print(f"\n[OK] Report written to {args.report}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
